name: Convert All Lists to YAML

on:
  #schedule:
    #- cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:      # 允许手动触发

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Convert .list Files to .yaml
      run: |
        # 创建 MyProviders 目录以存放生成的 yaml 文件
        mkdir -p Clash/MyProviders
        
        # 定义所有可能的前缀
        valid_prefixes="DOMAIN DOMAIN-SUFFIX DOMAIN-KEYWORD GEOIP IP-CIDR IP-CIDR6 SRC-IP-CIDR SRC-PORT DST-PORT PROCESS-NAME PROCESS-PATH USER-AGENT"
        
        for list_file in Clash/Ruleset/*.list; do
          # 提取文件名
          filename=$(basename "$list_file" .list)
          
          # 创建 .yaml 文件并添加 `payload` 字段
          echo "payload:" > "Clash/MyProviders/$filename.yaml"
          
          # 逐行读取 .list 文件并检查前缀是否匹配
          while IFS= read -r line; do
            for prefix in $valid_prefixes; do
              if [[ $line == "$prefix"* ]]; then
                echo "  - $line" >> "Clash/MyProviders/$filename.yaml"
                break
              fi
            done
          done < "$list_file"
        done

    - name: Commit and Push Converted Files
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add Clash/MyProviders/*.yaml
        git commit -m "Auto-converted .list files to .yaml"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
